=== KopterBuzz/NOMNOM/ValidationSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": ["id","displayName", "description", "authors", "artifacts", "urls"],
  "properties": {
    "id" : {"type": "string" },
    "displayName": { "type": "string" },
    "description": { "type": "string" },
    "tags" : {
      "type" : "array",
      "items" : {"type" : "string"}
    },
    "imageUrl": { "type": "string", "format": "uri" },
    "imageHash": { "type": "string" },
    "urls": { 
      "type": "array",
      "items": {
        "type" : "object",
        "required": ["name","url"],    
        "properties": {
          "name" : {"type": "string"},
          "url" : {"type": "string", "format" : "uri"}
        }    
      }
    },
    "authors": {
      "type": "array",
      "items": { "type": "string" }
    },
    "isClientOrServer": {
      "type": "string",
      "enum": ["Client", "Server", "Both"]
    },
    "githubOwner" : {"type": "string"},
    "githubRepoName" : {"type": "string"},
    "autoUpdateArtifacts" : {"type": "string"},
    "releaseTagPrefix": {"type": "string", "minLength": 1},
    "releaseAssetName": {"type": "string", "minLength": 1},
    "artifacts": {
      "type": "array",
      "items": {
        "type": "object",
        "required": ["fileName", "version", "downloadUrl", "category", "type"],
        "properties": {
          "fileName": { "type": "string" },
          "version": { "type": "string" },
          "category": { "type": "string"},
          "type": { "type": "string"},
          "gameVersion": { "type": "string" },
          "downloadUrl": { "type": "string", "format": "uri" },
          
          "extends": {
            "type": "object",
            "required" : ["id","version"],
            "properties": {
              "id" : { "type": "string" },
              "version": { "type": "string" }
            }
          },
          "dependencies": { 
            "type": "array",
            "items": {
              "type": "object",
              "required" : ["id","version"],
              "properties": {
                "id" : { "type": "string" },
                "version": { "type": "string" }
              }
            }
          },
          "incompatibilities": {
            "type": "array",
            "items": {
              "type": "object",
              "required" : ["id","version"],
              "properties": {
                "id" : { "type": "string" },
                "version": { "type": "string" }
              }
            }
          }
        }
      }
    }
  }
}

=== KopterBuzz/NOMNOM/modManifests/NOSmartEjector.json
{
  "id": "NOSmartEjector",
  "displayName": "NO Smart Ejector",
  "description": "Automated countermeasure ejection system flares for missile launch and radar lock defense in Nuclear Option.",
  "tags": [
    "QoL",
    "Utility",
    "Combat"
  ],
  "urls": [
    {
      "name": "info",
      "url": "https://github.com/PWFoox/NOSmartEjector"
    }
  ],
  "authors": [
    "PWFoox"
  ],
  "isClientOrServer": "Client",
  "githubOwner": "NOSmartEjector",
  "githubRepoName": "NOSmartEjector",
  "autoUpdateArtifacts": "True",
  "artifacts": [
    {
      "type": "plugin",
      "fileName": "NOSmartEjector-v1.1.zip",
      "version": "1.1",
      "category": "Release",
      "gameVersion": "0.34.2",
      "downloadUrl": "https://github.com/PWFoox/NOSmartEjector/releases/download/v1.1/NOSmartEjector-v1.1.zip",
      "hash": "sha256:1ab961ce90322fa55723a8a2f89231f81f2aa907a86961c4b7ae07085df5fcd0"
    }
  ]
}

=== KopterBuzz/NOMNOM/modManifests/navalloadout.json
{
  "id": "navalloadout",
  "displayName": "Naval Loadout",
  "description": "Customize the missile loadout for each naval asset",
  "tags": [
    "Naval",
    "Loadout"
  ],
  "urls": [
    {
      "name": "info",
      "url": "https://github.com/SonPamungkas/navalloadout"
    }
  ],
  "authors": [
    "Neutral Observer"
  ],
  "githubOwner": "SonPamungkas",
  "githubRepoName": "navalloadout",
  "autoUpdateArtifacts": "false",
  "artifacts": [
    {
      "fileName": "NavalLoadout.dll",
      "version": "1.0",
      "category": "Plugin",
      "type": "BepInEx",
      "gameVersion": "0.33.3",
      "downloadUrl": "",
      "hash": "",
      "dependencies": []
    }
  ]
}

=== KopterBuzz/NOMNOM/modManifests/tactical-laser-system_mod.json
{
  "id": "tactical-laser-system_mod",
  "displayName": "Tactical Laser System",
  "description": "Overpowering laser mod",
  "tags": [
    "Weapon",
    "Laser"
  ],
  "urls": [
    {
      "name": "info",
      "url": "https://github.com/SonPamungkas/tactical-laser-system_mod"
    }
  ],
  "authors": [
    "Neutral Observer"
  ],
  "githubOwner": "SonPamungkas",
  "githubRepoName": "tactical-laser-system_mod",
  "autoUpdateArtifacts": "false",
  "artifacts": [
    {
      "fileName": "com.tls.mod.dll",
      "version": "2.1",
      "category": "Plugin",
      "type": "BepInEx",
      "gameVersion": "0.33.3",
      "downloadUrl": "",
      "hash": "",
      "dependencies": []
    }
  ]
}

=== KopterBuzz/NOMNOM/modManifests/com.user.f4phantom.json
{
  "id": "com.user.f4phantom",
  "displayName": "F-4E Phantom II Mod",
  "description": "[WIP] f4 phantom with damagemodel and 6x bomb",
  "tags": [
    "plane"
  ],
  "urls": [
    {
      "name": "info",
      "url": "https://github.com/mon22144/NOMNOM-com-user-f4phantom"
    }
  ],
  "authors": [
    "Anomie"
  ],
  "githubOwner": "mon22144",
  "githubRepoName": "NOMNOM-com-user-f4phantom",
  "autoUpdateArtifacts": "True",
  "artifacts": [
    {
      "type": "plugin",
      "fileName": "com.user.f4phantom_v1.3.0.zip",
      "downloadUrl": "https://github.com/mon22144/NOMNOM-com-user-f4phantom/releases/download/v1.3.0/com.user.f4phantom_v1.3.0.zip",
      "hash": "sha256:93a6ea73c4b63450ef13914ee06f9d8def3309292aa44c224f79114b952faec4",
      "gameVersion": "0.32",
      "version": "1.3.0",
      "category": "Release"
    }
  ]
}

=== KopterBuzz/NOMNOM/modManifests/nomusicreplacer-remastered.json
{
  "id": "nomusicreplacer-remastered",
  "displayName": "Nuclear Option Music Replacer Remastered",
  "description": "A simple yet smart, futureproofed, and mod friendly music replacer for nuclear option",
  "tags": [
    "Audio",
    "Music"
  ],
  "urls": [
    {
      "name": "info",
      "url": "https://github.com/SonPamungkas/nomusicreplacer-remastered"
    }
  ],
  "authors": [
    "Neutral Observer"
  ],
  "githubOwner": "SonPamungkas",
  "githubRepoName": "nomusicreplacer-remastered",
  "autoUpdateArtifacts": "false",
  "artifacts": [
    {
      "fileName": "NOMusicReplacer.dll",
      "version": "1.1",
      "category": "Plugin",
      "type": "BepInEx",
      "gameVersion": "0.33.3",
      "downloadUrl": "",
      "hash": "",
      "dependencies": []
    }
  ]
}

=== KopterBuzz/NOMNOM/modManifests/LoyalWingman.json
{
  "id": "LoyalWingman",
  "displayName": "Loyal Wingman",
  "description": "Nuclear Option 0.34 compatibility prerelease of the Loyal Wingman plugin.",
  "authors": [
    "Loyal Wingman contributors"
  ],
  "urls": [
    {
      "name": "info",
      "url": "https://github.com/NOLoyalWingman/LoyalWingman"
    }
  ],
  "githubOwner": "NOLoyalWingman",
  "githubRepoName": "LoyalWingman",
  "autoUpdateArtifacts": "True",
  "artifacts": [
    {
      "fileName": "LoyalWingman.dll",
      "version": "0.0.2",
      "category": "preRelease",
      "type": "plugin",
      "gameVersion": "0.34",
      "downloadUrl": "https://github.com/NOLoyalWingman/LoyalWingman/releases/download/v0.0.2/LoyalWingman.dll",
      "hash": "sha256:91c9eefa32fe784a9adc852c27ba8c525f3dcd9d611d669aaa0070d88c4c5c6f",
      "dependencies": [
        {
          "id": "com.nikkorap.blueprinter",
          "version": "1.8.21"
        },
        {
          "id": "blueprinter.kestrel",
          "version": "2.2.0"
        }
      ]
    }
  ]
}

=== KopterBuzz/NOMNOM/modManifests/NuclearOptionVRFix.json
{
  "id": "NuclearOptionVRFix",
  "displayName": "FeelSoMoon",
  "description": "Nuclear Option Camera Fix for uuvr",
  "tags": [
    "mod","vr"
  ],
  "urls": [
    {
      "name": "info",
      "url": "https://github.com/FeelSoMoon/NuclearOptionVRFix"
    }
  ],
  "authors": [
    "FeelSoMoon"
  ],
  "githubOwner": "FeelSoMoon",
  "githubRepoName": "NuclearOptionVRFix",
  "autoUpdateArtifacts": "False",
  "artifacts": [
    {
      "fileName": "NuclearOptionVRFix.zip",
      "version": "1.0",
      "category": "release",
      "type": "plugin",
      "gameVersion": "0.32",
      "downloadUrl": "https://github.com/7ep3s/NuclearOptionVRFix/releases/download/1.0/NuclearOptionVRFix.zip",
      "hash": "sha256:b3ccd77e1bb78dcb42ee5b1797063252721db4027a7da117ff9914a457a3de9d",
      "dependencies" : [
        {
          "id": "uuvr",
          "version": "0.4.0"
        }
      ]
    }
  ]
}

=== KopterBuzz/NOMNOM/modManifests/navalname.json
{
  "id": "navalname",
  "displayName": "Naval Name",
  "description": "Automatic renaming of Naval Airbase",
  "tags": [
    "Naval",
    "Names"
  ],
  "urls": [
    {
      "name": "info",
      "url": "https://github.com/SonPamungkas/navalname"
    }
  ],
  "authors": [
    "Neutral Observer"
  ],
  "githubOwner": "SonPamungkas",
  "githubRepoName": "navalname",
  "autoUpdateArtifacts": "false",
  "artifacts": [
    {
      "fileName": "NavalNameMod.dll",
      "version": "1.2",
      "category": "Plugin",
      "type": "BepInEx",
      "gameVersion": "0.33.3",
      "downloadUrl": "",
      "hash": "",
      "dependencies": []
    }
  ]
}
